server:
  port: 8093

spring:
  application:
    name: inventory-service

  data:
    redis:
      host: ${REDIS_HOST:redis}
      port: ${REDIS_PORT:6379}
      timeout: ${REDIS_TIMEOUT:2s}

  datasource:
    url: ${INVENTORY_DB_URL:jdbc:postgresql://inventory-db:5432/inventory_db}
    username: ${INVENTORY_DB_USER:inventory_user}
    password: ${INVENTORY_DB_PASS:inventory_pass}

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://discovery-server:8761/eureka/}

logging:
  pattern:
    level: "%5p [${spring.application.name},traceId=%X{traceId},spanId=%X{spanId}]"

http:
  client:
    connect-timeout-seconds: ${HTTP_CLIENT_CONNECT_TIMEOUT_SECONDS:2}
    response-timeout-seconds: ${HTTP_CLIENT_RESPONSE_TIMEOUT_SECONDS:5}
    idle-evict-seconds: ${HTTP_CLIENT_IDLE_EVICT_SECONDS:30}

resilience4j:
  circuitbreaker:
    instances:
      accessService:
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 20
        minimumNumberOfCalls: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 3
        slowCallRateThreshold: 70
        slowCallDurationThreshold: 3000
        ignoreExceptions:
          - com.rumal.inventory_service.exception.ResourceNotFoundException
          - com.rumal.inventory_service.exception.ValidationException
          - com.rumal.inventory_service.exception.UnauthorizedException
      vendorService:
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 20
        minimumNumberOfCalls: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 3
        slowCallRateThreshold: 70
        slowCallDurationThreshold: 3000
        ignoreExceptions:
          - com.rumal.inventory_service.exception.ResourceNotFoundException
          - com.rumal.inventory_service.exception.ValidationException
          - com.rumal.inventory_service.exception.UnauthorizedException

  retry:
    instances:
      accessService:
        maxAttempts: 3
        waitDuration: 300ms
        enableExponentialBackoff: true
        exponentialBackoffMultiplier: 2
        retryExceptions:
          - java.io.IOException
          - org.springframework.web.client.ResourceAccessException
          - org.springframework.web.client.HttpServerErrorException
          - com.rumal.inventory_service.exception.ServiceUnavailableException
      vendorService:
        maxAttempts: 3
        waitDuration: 300ms
        enableExponentialBackoff: true
        exponentialBackoffMultiplier: 2
        retryExceptions:
          - java.io.IOException
          - org.springframework.web.client.ResourceAccessException
          - org.springframework.web.client.HttpServerErrorException
          - com.rumal.inventory_service.exception.ServiceUnavailableException

internal:
  auth:
    shared-secret: ${INTERNAL_AUTH_SHARED_SECRET:}

inventory:
  reservation:
    ttl-seconds: ${INVENTORY_RESERVATION_TTL_SECONDS:1800}
    cleanup-interval: ${INVENTORY_RESERVATION_CLEANUP_INTERVAL:PT1M}
