spring:
  application:
    name: wishlist-service

  data:
    redis:
      host: ${REDIS_HOST:redis}
      port: ${REDIS_PORT:6379}
      timeout: ${REDIS_TIMEOUT:2s}

  datasource:
    url: ${WISHLIST_DB_URL:jdbc:postgresql://wishlist-db:5432/wishlist_db}
    username: ${WISHLIST_DB_USER:wishlist_user}
    password: ${WISHLIST_DB_PASS:wishlist_pass}

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false

server:
  port: 8087

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://discovery-server:8761/eureka/}

logging:
  pattern:
    level: "%5p [${spring.application.name},traceId=%X{traceId},spanId=%X{spanId}]"

resilience4j:
  circuitbreaker:
    instances:
      productService:
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 20
        minimumNumberOfCalls: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 3
        slowCallRateThreshold: 70
        slowCallDurationThreshold: 3000
        ignoreExceptions:
          - com.rumal.wishlist_service.exception.ResourceNotFoundException
          - com.rumal.wishlist_service.exception.ValidationException
          - com.rumal.wishlist_service.exception.UnauthorizedException
      cartService:
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 20
        minimumNumberOfCalls: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 3
        slowCallRateThreshold: 70
        slowCallDurationThreshold: 3000
        ignoreExceptions:
          - com.rumal.wishlist_service.exception.ResourceNotFoundException
          - com.rumal.wishlist_service.exception.ValidationException
          - com.rumal.wishlist_service.exception.UnauthorizedException

  retry:
    instances:
      productService:
        maxAttempts: 3
        waitDuration: 300ms
        enableExponentialBackoff: true
        exponentialBackoffMultiplier: 2
        retryExceptions:
          - java.io.IOException
          - org.springframework.web.client.ResourceAccessException
          - org.springframework.web.client.HttpServerErrorException
      cartService:
        maxAttempts: 3
        waitDuration: 300ms
        enableExponentialBackoff: true
        exponentialBackoffMultiplier: 2
        retryExceptions:
          - java.io.IOException
          - org.springframework.web.client.ResourceAccessException
          - org.springframework.web.client.HttpServerErrorException

internal:
  auth:
    shared-secret: ${INTERNAL_AUTH_SHARED_SECRET:}

wishlist:
  max-items-per-collection: ${WISHLIST_MAX_ITEMS_PER_COLLECTION:200}

cache:
  wishlist-by-keycloak-ttl: ${CACHE_WISHLIST_BY_KEYCLOAK_TTL:45s}
